/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.codegen.tables.records;


import edu.java.scrapper.domain.jooq.codegen.tables.GithubRelease;

import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubReleaseRecord extends UpdatableRecordImpl<GithubReleaseRecord> implements Record3<Long, Long, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GITHUB_RELEASE.ID</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>GITHUB_RELEASE.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>GITHUB_RELEASE.REPO_ID</code>.
     */
    public void setRepoId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>GITHUB_RELEASE.REPO_ID</code>.
     */
    @Nullable
    public Long getRepoId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>GITHUB_RELEASE.PUBLISHED_AT</code>.
     */
    public void setPublishedAt(@NotNull OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>GITHUB_RELEASE.PUBLISHED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, OffsetDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return GithubRelease.GITHUB_RELEASE.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return GithubRelease.GITHUB_RELEASE.REPO_ID;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field3() {
        return GithubRelease.GITHUB_RELEASE.PUBLISHED_AT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getRepoId();
    }

    @Override
    @NotNull
    public OffsetDateTime component3() {
        return getPublishedAt();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getRepoId();
    }

    @Override
    @NotNull
    public OffsetDateTime value3() {
        return getPublishedAt();
    }

    @Override
    @NotNull
    public GithubReleaseRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubReleaseRecord value2(@Nullable Long value) {
        setRepoId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubReleaseRecord value3(@NotNull OffsetDateTime value) {
        setPublishedAt(value);
        return this;
    }

    @Override
    @NotNull
    public GithubReleaseRecord values(@NotNull Long value1, @Nullable Long value2, @NotNull OffsetDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GithubReleaseRecord
     */
    public GithubReleaseRecord() {
        super(GithubRelease.GITHUB_RELEASE);
    }

    /**
     * Create a detached, initialised GithubReleaseRecord
     */
    @ConstructorProperties({ "id", "repoId", "publishedAt" })
    public GithubReleaseRecord(@NotNull Long id, @Nullable Long repoId, @NotNull OffsetDateTime publishedAt) {
        super(GithubRelease.GITHUB_RELEASE);

        setId(id);
        setRepoId(repoId);
        setPublishedAt(publishedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GithubReleaseRecord
     */
    public GithubReleaseRecord(edu.java.scrapper.domain.jooq.codegen.tables.pojos.GithubRelease value) {
        super(GithubRelease.GITHUB_RELEASE);

        if (value != null) {
            setId(value.getId());
            setRepoId(value.getRepoId());
            setPublishedAt(value.getPublishedAt());
            resetChangedOnNotNull();
        }
    }
}
