CREATE TABLE IF NOT EXISTS Link
(
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    url TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    checked_at TIMESTAMP WITH TIME ZONE,

    PRIMARY KEY (id)
);
