app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 300000
  database-access-type: jooq
  retry:
    http-statuses: 500, 503, 504
    type: constant
    max-attempts: 7
    config:
      initial-interval-millis: 1000
      max-interval-millis: 30000
      multiplier: 2
  kafka-config:
    bootstrap-servers: localhost:9092
    topic-config:
      name: updates
      partitions: 2
      replicas: 1
  use-queue: true
  git-hub-token: unset

spring:
  application:
    name: scrapper
  cache:
    cache-names:
      - scrapper-rate-limit
    caffeine:
      spec: maximumSize=200000,expireAfterAccess=60s
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

server:
  port: 8080

bucket4j:
  filters:
    - cache-name: scrapper-rate-limit
      http-response-body: "{\"status\": 503, \"error\": \"Service Unavailable\", \"message\": \"Service Unavailable\"}"
      rate-limits:
        - bandwidths:
            - capacity: 100
              refill-speed: interval
              time: 1
              unit: minutes
      url: /.*

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
