/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.codegen.tables;


import edu.java.scrapper.domain.jooq.codegen.DefaultSchema;
import edu.java.scrapper.domain.jooq.codegen.Keys;
import edu.java.scrapper.domain.jooq.codegen.tables.records.GithubPullRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubPull extends TableImpl<GithubPullRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GITHUB_PULL</code>
     */
    public static final GithubPull GITHUB_PULL = new GithubPull();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<GithubPullRecord> getRecordType() {
        return GithubPullRecord.class;
    }

    /**
     * The column <code>GITHUB_PULL.ID</code>.
     */
    public final TableField<GithubPullRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>GITHUB_PULL.REPO_ID</code>.
     */
    public final TableField<GithubPullRecord, Long> REPO_ID = createField(DSL.name("REPO_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>GITHUB_PULL.CREATED_AT</code>.
     */
    public final TableField<GithubPullRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private GithubPull(Name alias, Table<GithubPullRecord> aliased) {
        this(alias, aliased, null);
    }

    private GithubPull(Name alias, Table<GithubPullRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>GITHUB_PULL</code> table reference
     */
    public GithubPull(String alias) {
        this(DSL.name(alias), GITHUB_PULL);
    }

    /**
     * Create an aliased <code>GITHUB_PULL</code> table reference
     */
    public GithubPull(Name alias) {
        this(alias, GITHUB_PULL);
    }

    /**
     * Create a <code>GITHUB_PULL</code> table reference
     */
    public GithubPull() {
        this(DSL.name("GITHUB_PULL"), null);
    }

    public <O extends Record> GithubPull(Table<O> child, ForeignKey<O, GithubPullRecord> key) {
        super(child, key, GITHUB_PULL);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<GithubPullRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    @NotNull
    public List<ForeignKey<GithubPullRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_D8);
    }

    private transient GithubRepository _githubRepository;

    /**
     * Get the implicit join path to the <code>PUBLIC.GITHUB_REPOSITORY</code>
     * table.
     */
    public GithubRepository githubRepository() {
        if (_githubRepository == null)
            _githubRepository = new GithubRepository(this, Keys.CONSTRAINT_D8);

        return _githubRepository;
    }

    @Override
    @NotNull
    public GithubPull as(String alias) {
        return new GithubPull(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GithubPull as(Name alias) {
        return new GithubPull(alias, this);
    }

    @Override
    @NotNull
    public GithubPull as(Table<?> alias) {
        return new GithubPull(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubPull rename(String name) {
        return new GithubPull(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubPull rename(Name name) {
        return new GithubPull(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubPull rename(Table<?> name) {
        return new GithubPull(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
