/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.codegen.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Chat implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private OffsetDateTime registrationDate;

    public Chat() {}

    public Chat(Chat value) {
        this.id = value.id;
        this.registrationDate = value.registrationDate;
    }

    @ConstructorProperties({ "id", "registrationDate" })
    public Chat(
        @NotNull Long id,
        @Nullable OffsetDateTime registrationDate
    ) {
        this.id = id;
        this.registrationDate = registrationDate;
    }

    /**
     * Getter for <code>CHAT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>CHAT.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>CHAT.REGISTRATION_DATE</code>.
     */
    @Nullable
    public OffsetDateTime getRegistrationDate() {
        return this.registrationDate;
    }

    /**
     * Setter for <code>CHAT.REGISTRATION_DATE</code>.
     */
    public void setRegistrationDate(@Nullable OffsetDateTime registrationDate) {
        this.registrationDate = registrationDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Chat other = (Chat) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.registrationDate == null) {
            if (other.registrationDate != null)
                return false;
        }
        else if (!this.registrationDate.equals(other.registrationDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.registrationDate == null) ? 0 : this.registrationDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chat (");

        sb.append(id);
        sb.append(", ").append(registrationDate);

        sb.append(")");
        return sb.toString();
    }
}
