/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.codegen.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubPull implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long repoId;
    private OffsetDateTime createdAt;

    public GithubPull() {}

    public GithubPull(GithubPull value) {
        this.id = value.id;
        this.repoId = value.repoId;
        this.createdAt = value.createdAt;
    }

    @ConstructorProperties({ "id", "repoId", "createdAt" })
    public GithubPull(
        @NotNull Long id,
        @Nullable Long repoId,
        @NotNull OffsetDateTime createdAt
    ) {
        this.id = id;
        this.repoId = repoId;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>GITHUB_PULL.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>GITHUB_PULL.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>GITHUB_PULL.REPO_ID</code>.
     */
    @Nullable
    public Long getRepoId() {
        return this.repoId;
    }

    /**
     * Setter for <code>GITHUB_PULL.REPO_ID</code>.
     */
    public void setRepoId(@Nullable Long repoId) {
        this.repoId = repoId;
    }

    /**
     * Getter for <code>GITHUB_PULL.CREATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>GITHUB_PULL.CREATED_AT</code>.
     */
    public void setCreatedAt(@NotNull OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GithubPull other = (GithubPull) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.repoId == null) {
            if (other.repoId != null)
                return false;
        }
        else if (!this.repoId.equals(other.repoId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.repoId == null) ? 0 : this.repoId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GithubPull (");

        sb.append(id);
        sb.append(", ").append(repoId);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
