/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.codegen;


import edu.java.scrapper.domain.jooq.codegen.tables.Chat;
import edu.java.scrapper.domain.jooq.codegen.tables.ChatLink;
import edu.java.scrapper.domain.jooq.codegen.tables.GithubCommit;
import edu.java.scrapper.domain.jooq.codegen.tables.GithubPull;
import edu.java.scrapper.domain.jooq.codegen.tables.GithubRelease;
import edu.java.scrapper.domain.jooq.codegen.tables.GithubRepository;
import edu.java.scrapper.domain.jooq.codegen.tables.Link;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>CHAT_LINK</code>.
     */
    public static final ChatLink CHAT_LINK = ChatLink.CHAT_LINK;

    /**
     * The table <code>GITHUB_COMMIT</code>.
     */
    public static final GithubCommit GITHUB_COMMIT = GithubCommit.GITHUB_COMMIT;

    /**
     * The table <code>GITHUB_PULL</code>.
     */
    public static final GithubPull GITHUB_PULL = GithubPull.GITHUB_PULL;

    /**
     * The table <code>GITHUB_RELEASE</code>.
     */
    public static final GithubRelease GITHUB_RELEASE = GithubRelease.GITHUB_RELEASE;

    /**
     * The table <code>GITHUB_REPOSITORY</code>.
     */
    public static final GithubRepository GITHUB_REPOSITORY = GithubRepository.GITHUB_REPOSITORY;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;
}
